language: python

script:
  - tox

addons:
  apt:
    packages:
      - slapd
      - ldap-utils

install:
  - pip install tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38

    # Pypy
    - python: "pypy3"
      env: TOXENV=pypy3

    # Linting
    - python: "3.8"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
